.github/ISSUE_TEMPLATE/refator.yml, .github/ISSUE_TEMPLATE/✅-feature.md, .github/ISSUE_TEMPLATE/❌-bug.md
- 이슈 템플릿 조금 추가했습니다!
- Refactor ISSUE 템플릿 추가하였습니다.
=> [#2] ISSUE 템플릿 수정

.github/workflows/main.yml, src/app/(afterLogin)/[username]/page.tsx, src/app/(beforeLogin)/login/page.tsx
=> [#6] Git Action CI 설정

.github/ISSUE_TEMPLATE/chore.yml, .github/ISSUE_TEMPLATE/fix.yml, .github/ISSUE_TEMPLATE/style.yml
=> [#9] issue 템플릿 기능 추가

src/app/globals.css, src/app/layout.tsx, tailwind.config.ts
폰트 경로 수정 및 테일윈드 설정 추가
어떤 변경 사항이 있나요?
PR이 다음 요구 사항을 충족하는지 확인하세요.
=> [#5] 글꼴 적용

.github/auto_assign.yml
=> [#16]: auto-assign 생성

.github/auto_assign.yml
[#70 ] : Auto Assign 설정 변경
close #70 
resolved:#70
=> [#70] : Auto Assign 설정 변경

src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx
[#80 ] : 대시보드 수정페이지 헤더,사이드바 적용 CSS 수정
close #80 
resolved:#80
=> [#80] 대시보드 수정페이지 헤더,사이드바 적용 CSS 수정

src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx, src/app/_api/Dashboards/index.ts
[#75] 대시보드 수정페이지 페이지네이션
close #75 
resolved:#75
=> [#75] 대시보드 수정페이지 페이지네이션

package-lock.json, package.json, src/app/_recoil/AuthAtom/index.ts
[#112] : Recoil 새로고침 문제 Fix
close #112
resolved:#112
=> [#112] Recoil 새로고침 문제 Fix

src/app/(afterLogin)/_component/Header/index.tsx, src/app/_component/Chip/Tag/index.tsx, src/app/_component/InputForm/TagInput.tsx, src/app/_constant/Chip.ts
[#122] Tag, Header 컴포넌트 리펙토링
close #122 
resolved:#122
- 태그 랜덤 색상, 글자제한(공백포함 10글자)
- 헤더 리코일 적용
=> [#122] Tag, Header 컴포넌트 리펙토링

package-lock.json, package.json, src/app/(afterLogin)/_component/InvitationDashboard/InvitationList.tsx, src/app/(afterLogin)/_component/InvitationDashboard/index.tsx, src/app/(afterLogin)/_component/SideMenu/index.tsx, src/app/_api/Dashboards/index.ts, src/app/_hook/useInfiniteScroll.tsx, tailwind.config.ts, tsconfig.json
[#120] : 초대받은 대시보드 무한스크롤 & 초대 수락/거절
close #120
resolved:#120
api 응답에 대시보드의 색상이 들어있지 않아서 일단 대시보드 목록을 다시 불러오도록 해뒀습니당
=> [#120] 초대받은 대시보드 무한스크롤 & 초대 수락/거절

.eslintrc, package-lock.json, package.json, public/icons/line.svg, src/app/(afterLogin)/_component/Card/index.tsx, src/app/(afterLogin)/_component/CardList/index.tsx, src/app/(afterLogin)/_component/DashboardList/index.tsx, src/app/(afterLogin)/_component/InvitationDashboard/index.tsx, src/app/(afterLogin)/_component/SideMenu/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx, src/app/_api/card/index.tsx, src/app/_component/Button/Cancel/index.tsx, src/app/_component/Button/Confirm/index.tsx, src/app/_component/Chip/Tag/index.tsx, src/app/_component/Input/InputField.tsx, src/app/_component/InputForm/InputStyle.tsx, src/app/_component/InputForm/TagInput.tsx, src/app/_component/InputForm/index.tsx, src/app/_component/dropdown/filter/index.tsx, src/app/_component/dropdown/index.tsx, src/app/_component/modal/ModalLayout.tsx, src/app/_component/modal/column/index.tsx, src/app/_component/modal/index.tsx, src/app/_component/modal/toDoCard/DetailComponent.tsx, src/app/_component/modal/toDoCard/index.tsx, src/app/_hook/usePutCard.tsx, src/app/_util/returnModal.tsx, src/app/globals.css, tailwind.config.ts
[#125 ] : 제목
close #
resolved:#
=> [#125] 전체 모달 스타일 수정

src/app/(afterLogin)/_component/Card/index.tsx, src/app/_component/Button/Confirm/index.tsx, src/app/_component/InputForm/CommentInput.tsx, src/app/_component/InputForm/DateInput.tsx, src/app/_component/InputForm/InputStyle.tsx, src/app/_component/InputForm/TagInput.tsx, src/app/_component/InputForm/index.tsx, src/app/_component/dropdown/filter/index.tsx, src/app/_component/modal/column/index.tsx, src/app/_component/modal/toDoCard/index.tsx, src/app/_util/axiosInstance.tsx
[#119] : /mypage, 모달 인풋 리팩토링
close #119
resolved:#119
`대시보드`
`댓글`
`컬럼관리`
`할일생성`
`인풋 초기화`
=> [#119] /mypage, 모달 인풋 리팩토링

package-lock.json, src/app/_component/dropdown/filter/index.tsx, src/app/_component/modal/toDoCard/DetailComponent.tsx
[#이슈번호] : 제목
close #
resolved:#
=> feat: 담당자 및 댓글 프로필 이미지  전부 동그라미로 변경

src/app/(afterLogin)/_component/CardList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx, src/app/_component/modal/column/index.tsx, src/app/_component/modal/toDoCard/index.tsx, src/app/_hook/usePutCard.tsx
[#이슈번호] : 제목
close #
resolved:#
=> fix/#134 : 에러처리 수정

src/app/(afterLogin)/_component/SideMenu/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
- 대시보드 리스트 배경색상
- 태블릿 이하 대시보드 비어있을 때 기본 높이
- 대시보드 이동 시 칼럼 추가 버튼이 먼저 보이는 현상수정
[#152] : 스타일 수정
close #152
resolved:#152
=> [#152] 스타일 수정

src/app/(afterLogin)/_component/Header/index.tsx, src/app/(afterLogin)/_util/submitInvitation.ts, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx, src/app/_api/Dashboards/index.ts, src/app/_component/modal/dashBoard/index.tsx, src/app/_constant/Input.ts, src/app/_recoil/dashboardAtom/index.ts
[#161 ] : 초대 내역 수정
close #
resolved:#
=> [#161] 초대 내역 수정

src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
[#170] 드래그 앤 드롭 영역이 보이도록 수정
close #170
resolved:#170
=> [#170] 드래그 앤 드롭 영역이 보이도록 수정

next.config.js, src/app/(afterLogin)/@modal/default.tsx, src/app/(afterLogin)/_component/Header/HeaderDropdown.tsx, src/app/(afterLogin)/_component/Header/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx, src/app/(afterLogin)/layout.tsx, src/app/_component/modal/index.tsx, src/app/_component/modal/toDoCard/index.tsx, src/app/_hook/useRenderModal.tsx, src/app/_recoil/Dropdown/index.ts
[#171 ] : 대시보드 권한x 관리, 초대 버튼x
close #
resolved:#
=> [#171] 대시보드 권한x 관리, 초대 버튼x

src/app/(afterLogin)/_component/Card/index.tsx, src/app/(afterLogin)/_component/SideMenu/index.tsx, src/app/_component/Button/CardDashboard/index.tsx, src/app/_component/modal/column/index.tsx, src/app/_constant/Input.ts
[#이슈번호] : 스타일 QA 수정
close #168
resolved:#168
`사이드 메뉴 스크롤바`
`컬럼 추가, 관리 글자수 제한`
`myboard의 대시보드명 말줄임 처리`
`할일 카드 달력 날짜 가운데 정렬`
`pc 전, 후`
`태블릿 전, 후`
=> [#168] 스타일 QA 수정

src/app/(beforeLogin)/login/page.tsx, src/app/_recoil/AuthAtom/index.ts
[#이슈번호] : 로그인 실패시 alert와 모달 겹치는 문제
close #
resolved:#
=> Bug/login 로그인 실패시 alert와 모달 겹치는 문제

src/app/(afterLogin)/_component/Card/index.tsx, src/app/(afterLogin)/_component/CardList/index.tsx, src/app/_component/modal/column/index.tsx, src/app/_component/modal/toDoCard/detail/index.tsx, src/app/_component/modal/toDoCard/update/index.tsx, src/app/_recoil/CardAtom/index.tsx
[#이슈번호] : 제목
close #
resolved:#
=> [#159]: 모달리팩토링

src/app/_component/InputForm/DateInput.tsx, src/app/_component/modal/toDoCard/update/index.tsx
- 모바일 크롬에서 datepicker가 닫히는 현상 수정
- 할 일 수정 날짜 고정되던 현상 수정
[#182] QA 수정
close #182
resolved:#182
=> [#182] QA 수정

src/app/(afterLogin)/mypage/ProfileEdit/index.tsx, src/app/(afterLogin)/mypage/UserEditLayout/index.tsx
[#184 ] : 제목
close #
resolved:#
=> [#184] feat: 다크모드 미구현 적용

package-lock.json, package.json, src/app/(afterLogin)/_component/Header/HeaderDropdown.tsx, src/app/(afterLogin)/_component/InvitationDashboard/index.tsx, src/app/(afterLogin)/_component/SideMenu/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx, src/app/(afterLogin)/layout.tsx, src/app/(afterLogin)/mypage/PasswordEdit/index.tsx, src/app/(afterLogin)/mypage/ProfileEdit/index.tsx
[#192 ] : refactor : toast 기능 추가
close #192
resolved:#192
=> [#192] refactor : toast 기능 추가

src/app/_util/axiosErrors.tsx, src/app/_util/axiosInstance.tsx, src/app/_util/getErrorMessages.ts
[#188] API 공통 에러메세지 파싱 로직 수정
close #188 
resolved:#188
=> [#188] refactor : API 공통 에러메세지 파싱 로직 수정

src/app/_component/InputForm/PasswordCheck.tsx, src/app/_component/InputForm/PasswrdInput.tsx
[#191] 모바일 계정관리 페이지
close #191
resolved:#191
=> [#191] 모바일 계정관리 페이지

src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/EditBoard/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/InviteList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/_component/MemberList/index.tsx, src/app/(afterLogin)/dashboard/[dashboardId]/edit/page.tsx, src/app/_util/SelectAlert/index.tsx
[#이슈번호] : 제목
close #195 
resolved:#195
=> [#195] 수정 ,변경 ,삭제 이벤트 모달

src/app/(afterLogin)/_component/SideMenu/index.tsx
[#190] 사이드메뉴의 선택된 대시보드에 다크모드 배경 적용
close #190
resolved:#190
=> [#190] 사이드메뉴의 선택된 대시보드에 다크모드 배경 적용

src/app/(afterLogin)/_component/SideMenu/index.tsx
[#190] css 수정
close #190
resolved:#190
=> [#190] css 수정

src/app/(afterLogin)/dashboard/[dashboardId]/page.tsx
[#205 ] : 제목
close #
resolved:#
=> [#205] feat: 수평 스크롤 구현
